export const protocols = [
    {label: 'GRPC协议', value: 'grpc'},
    {label: 'MTLS协议', value: 'mtls'},
    {label: 'TLS协议', value: 'tls'},
    {label: 'TCP协议', value: 'tcp'},
    {label: 'MWSS协议', value: 'mwss'},
    {label: 'WSS协议', value: 'wss'},
    {label: 'MWS协议', value: 'mws'},
    {label: 'WS协议', value: 'ws'},
    {label: 'H2协议', value: 'h2'},
    {label: 'H2C协议', value: 'h2c'},
    {label: 'H3协议', value: 'h3'},
    {label: 'OTLS协议', value: 'otls'},
    {label: 'OHTTP协议', value: 'ohttp'},
    {label: 'PHTS协议', value: 'phts'},
    {label: 'PHT协议', value: 'pht'},
    {label: 'QUIC协议', value: 'quic'},
    {label: 'KCP协议', value: 'kcp'},
    {label: 'UDP协议', value: 'udp'},
]