name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./web
        run: npm install

      - name: Build frontend
        working-directory: ./web
        run: npm run build

      - name: Compress dist directory
        working-directory: ./web
        run: zip -r dist.zip dist

      - name: Move dist.zip to backend directory
        run: mv web/dist.zip server/web/

      - name: Build backend
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean --timeout 300m --parallelism=2
          workdir: ./server

      - name: Upload server release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ./server/dist/*.tar.gz
            ./server/dist/*.zip

      - name: Remove server file
        run: rm -rf ./server/dist

  gostc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build client
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean --timeout 300m --parallelism=2
          workdir: ./client

      - name: Upload client release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ./client/dist/*.tar.gz
            ./client/dist/*.zip

      - name: Remove client file
        run: rm -rf ./client/dist

  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build proxy
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean --timeout 300m --parallelism=2
          workdir: ./proxy

      - name: Upload release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ./proxy/dist/*.tar.gz
            ./proxy/dist/*.zip

      - name: Remove proxy file
        run: rm -rf ./proxy/dist